name: GitHub Actions Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies too
        run: npm i
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        